# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: T
      uses: EasyDesk/action-dotnet-test@v1.0.0
      # with:
      #   # Additional arguments to pass to 'dotnet test'.
      #   test-args: # optional
      #   # The build configuration to use (defaults to 'Release').
      #   build-configuration: # optional, default is Release
      #   # The path to the project or solution to test (defaults to the current directory).
      #   path: # optional, default is .
      #   # Whether or not to skip the build using the '--no-build' flag (defaults to true).
      #   skip-build: # optional, default is true
