# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.3.0
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
        dotnet-version: 8.0.x
    - name: new
      run: |
        dotnet new nunit -n benchTmp
        tree .
        cp BenchEntry/.* benchTmp
        tree benchTmp
          
    - name: T
      uses: EasyDesk/action-dotnet-test@v1.0.0
      with:
      #   # Additional arguments to pass to 'dotnet test'.
      #   test-args: # optional
      #   # The build configuration to use (defaults to 'Release').
      #   build-configuration: # optional, default is Release
      #   # The path to the project or solution to test (defaults to the current directory).
        path: benchTmp # optional, default is .
      #   # Whether or not to skip the build using the '--no-build' flag (defaults to true).
        skip-build: false # optional, default is true
