# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare  -  Checkout Code
      uses: actions/checkout@v4
    - name: Prepare  -  Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 8.0.x
        
    - name: Run  -  Opt
      run: |
        dotnet new nunit -n bench
        tree

        echo " "
        cat bench/UnitTest1.cs
        rm bench/UnitTest1.cs
        mv BenchEntry/Entry.cs bench/Entry.cs
        cat bench/Entry.cs
       
        echo " "
        cat bench/bench.csproj
        mv BenchEntry/bench.csproj bench/bench.csproj
        cat bench/bench.csproj
        
        mv BenchEntry/GlobalUsings.cs bench/GlobalUsings.cs
        
        sudo apt-get update
        sudo apt-get install -y mono-complete
        mkdir -p build/Output
        mcs /target:library /out:build/Output/AddMulTest.dll testcase/AddMulTest.cs
        
    - name: Test  -  Build BenchMark
      uses: EasyDesk/action-dotnet-build@v1.0.0
      with:
        path: bench
    - name: Test  -  Run BenchMark
      uses: EasyDesk/action-dotnet-test@v1.0.0
      with:
        path: bench
        test-args: -v n

