# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare  -  Checkout Code
      uses: actions/checkout@v4
    - name: Prepare  -  Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 8.0.x

    - name: Run  -  Opt
      run: |
        mkdir -p build/Output
        csc testcase/test1.cs -o build/Output/test1.dll
        
    - name: new
      run: |
        dotnet new nunit -n bench
        cp BenchEntry/*.cs bench
          
    - name: Test  -  Build BenchMark
      uses: EasyDesk/action-dotnet-build@v1.0.0
      with:
        path: bench # optional, default is .
        arg: --lib build/Output
    - name: Test  -  Run BenchMark
      uses: EasyDesk/action-dotnet-test@v1.0.0
      with:
        path: bench # optional, default is .
        test-args: -v n

